version: "3.8"
services:
  frontend:
    build:
      context: ./frontend        
      dockerfile: Dockerfile     
    ports:
      - "9567:9567"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend         
      dockerfile: Dockerfile     
    ports:
      - "8500:8500"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"  
    volumes:
      - esdata:/usr/share/elasticsearch/data  

volumes:
  esdata: